#!/usr/bin/env python
import requests
import argparse

def fake_words(limit):
    response = requests.get("http://wordgenerator.net/application/p.php",
                         params={"id":"fake_words",
                                 "type":50})
    words = response.text.split(",")
    return words[:limit]

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("limit", nargs="?", type=int,
                        help="How many words to print.")
    parser.add_argument("-s", "--separator", nargs="?", type=str,
                        help="A string to separate each word.")
    args = parser.parse_args()

    limit = args.limit or 1
    separator = args.separator or ", "

    words = fake_words(limit)

    print(separator.join(words).strip(separator))
