#!/usr/bin/env python
import sys
import requests

def lyrics(title, artist):
    r = requests.get("http://makeitpersonal.co/lyrics",
                     params={"artist": artist,
                             "title": title})
    return r.text

if __name__ == "__main__":
    if (len(sys.argv) < 3):
        print("Usage: lyrics [TITLE] [ARTIST]")
        exit(1)
    text = lyrics(sys.argv[1], sys.argv[2])
    print(text.encode())

