#!/usr/bin/env python
import random

with open('/usr/share/dict/words') as words:
    all_words = words.readlines()
    random_four = random.sample(all_words, 4)
    print("".join(random_four).replace("\n", ""))
