#!/usr/bin/env python
import random
import sys
import string

def random_string(size=6, chars=string.letters):
    return ''.join(random.choice(chars) for _ in range(size))

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: randomchars [NUMBER]")
        exit(1)

    print(random_string(size=int(sys.argv[1])))
